// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanArchitectureAssistant;

internal sealed partial class Vsix
{
    public const string Id = "CleanArchitectureAssistant.81a8eada-9fb6-4859-a99e-cb53387c1d1a";
    public const string Name = "CleanArchitectureAssistant";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "saman azadi";
    public const string Tags = "";
}