// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanArchitectureAssistant;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string CleanArchitectureAssistantString = "198ac80b-4443-43c2-967b-4471de2d25c0";
    public static Guid CleanArchitectureAssistant = new Guid(CleanArchitectureAssistantString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int ShowMainWindowCommand = 0x0100;
}